repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-case-conflict
    -   id: check-xml
    -   id: end-of-file-fixer
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v1.6.1
    hooks:
    -   id: pretty-format-java
        args: ["--autofix"]
